import assert from "node:assert/strict";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import { join } from "node:path";
import test from "node:test";
import { applyStructuredPatch } from "../../src/application/execution-handlers/structured-patch.js";

async function fixture(content = "one\ntwo\nthree\nfour\nfive\n") { const directory = await mkdtemp(join(os.tmpdir(), "forge-structured-patch-")); const filePath = join(directory, "file.txt"); await writeFile(filePath, content); return { directory, filePath }; }

test("replaces an inclusive line range", async () => { const { directory, filePath } = await fixture(); try { const result = await applyStructuredPatch(filePath, [{ type: "replace_lines", start: 2, end: 3, new_content: "TWO\nTHREE" }]); assert.equal(result.success, true); assert.equal(await readFile(filePath, "utf8"), "one\nTWO\nTHREE\nfour\nfive\n"); } finally { await rm(directory, { recursive: true, force: true }); } });
test("inserts content after a line", async () => { const { directory, filePath } = await fixture(); try { const result = await applyStructuredPatch(filePath, [{ type: "insert_after_line", line: 2, content: "inserted" }]); assert.equal(result.success, true); assert.equal(await readFile(filePath, "utf8"), "one\ntwo\ninserted\nthree\nfour\nfive\n"); } finally { await rm(directory, { recursive: true, force: true }); } });
test("applies multiple operations from bottom to top without shifting locations", async () => { const { directory, filePath } = await fixture(); try { const result = await applyStructuredPatch(filePath, [{ type: "insert_after_line", line: 1, content: "after-one" }, { type: "replace_lines", start: 4, end: 5, new_content: "FOUR\nFIVE" }]); assert.equal(result.success, true); assert.equal(await readFile(filePath, "utf8"), "one\nafter-one\ntwo\nthree\nFOUR\nFIVE\n"); } finally { await rm(directory, { recursive: true, force: true }); } });
test("validates all operations before applying any operation", async () => { const { directory, filePath } = await fixture(); try { const result = await applyStructuredPatch(filePath, [{ type: "replace_lines", start: 1, end: 1, new_content: "changed" }, { type: "insert_after_line", line: 99, content: "invalid" }]); assert.equal(result.success, false); assert.equal(result.error_code, "PATCH_NOT_APPLICABLE"); assert.equal(result.detail.operation_index, 1); assert.equal(await readFile(filePath, "utf8"), "one\ntwo\nthree\nfour\nfive\n"); } finally { await rm(directory, { recursive: true, force: true }); } });
test("dry_run returns the result without backup or write", async () => { const { directory, filePath } = await fixture(); let called = false; try { const result = await applyStructuredPatch(filePath, [{ type: "replace_lines", start: 2, end: 2, new_content: "TWO" }], { dry_run: true, backupFile: async () => { called = true; } }); assert.equal(result.success, true); assert.equal(called, false); assert.equal(result.detail.content, "one\nTWO\nthree\nfour\nfive\n"); assert.equal(await readFile(filePath, "utf8"), "one\ntwo\nthree\nfour\nfive\n"); } finally { await rm(directory, { recursive: true, force: true }); } });
