import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

const ui = readFileSync(new URL("../../web/src/main.jsx", import.meta.url), "utf8");
const client = readFileSync(new URL("../../web/src/services/node-client.js", import.meta.url), "utf8");

test("Agent Settings UI presents a masked, Node-only settings flow for every panel", () => {
  assert.match(ui, /function AgentSettingsOverlay/);
  assert.match(ui, /type="password"/);
  assert.match(ui, /placeholder="\*{8}"/);
  assert.match(ui, /Save Profile/);
  assert.match(ui, /Test Connection/);
  assert.match(ui, /setKey\(""\)/);
  assert.match(ui, /Connected: \$\{result\.status\}/);
  assert.match(ui, /Failed: \$\{error\.message\}/);
  assert.match(ui, /function mergeStreamMessage/);
  assert.match(ui, /correlation_id === message\.correlation_id/);
  assert.match(ui, /current\.text\}\$\{message\.payload\?\.text/);
  assert.match(ui, /natural-conversation/);
  assert.match(ui, /Architecture Manager is working…/);
  assert.match(ui, /<textarea/);
  assert.match(ui, /event\.key === "Enter" && !event\.shiftKey/);
  assert.doesNotMatch(ui, /<HumanDecisionActions client=\{client\} onWorkspaceChanged=\{onWorkspaceChanged\}/);
  assert.match(ui, /natural-message/);
  assert.doesNotMatch(ui, /requestAnimationFrame|pendingDeltas/);
  assert.match(ui, /Architecture Manager messages/);
  assert.match(ui, /role="tablist"/);
  assert.match(ui, /role="tab"/);
  assert.match(ui, /aria-selected/);
  assert.match(ui, /tab-bar/);
  assert.match(ui, /tab-button/);
  assert.match(ui, /is-active/);
  assert.match(ui, /CONVERSATIONS/);
  assert.match(ui, /CONV-ARCHITECTURE/);
  assert.match(ui, /CONV-SPRINT-LEADER/);
  assert.match(ui, /CONV-BUILDER/);
  assert.match(ui, /CONV-REVIEWER/);
  assert.match(ui, /PROVIDER_OPTIONS/);
  assert.match(ui, /codex/);
  assert.match(ui, /claude/);
  assert.match(ui, /openai/);
  assert.match(ui, /anthropic/);
  assert.match(ui, /custom/);
  assert.match(ui, /Provider/);
  assert.match(ui, /<select/);
  assert.match(ui, /provider/);
  assert.match(ui, /setProvider/);
  assert.match(ui, /model/);
  assert.match(ui, /setModel/);
  assert.match(ui, /workingByAgent/);
  assert.match(ui, /isWorking/);
  assert.match(ui, /disabled=\{isWorking\}/);
  assert.match(ui, /working-dot/);
  assert.match(ui, /is-working/);
  assert.match(ui, /activeAgent === "architecture-manager"/);
  assert.match(ui, /InlineDecisionControls/);
  assert.match(ui, /Approve/);
  assert.match(ui, /Reject/);
  assert.match(ui, /Request Changes/);
  assert.match(ui, /connectConversationStream/);
  assert.match(ui, /MODEL_CATALOG/);
  assert.match(ui, /getPendingArchitectureProposal/);
  assert.match(ui, /getLatestCompletedDecision/);
  assert.match(ui, /labelForDecision/);
  assert.match(ui, /decision-result/);
  assert.match(ui, /changeProvider/);
  assert.match(ui, /No model catalog/);
  assert.match(ui, /Select model/);
  assert.match(ui, /settings-mask/);
  assert.match(client, /requestJson\("\/agents\/settings"/);
  assert.match(client, /requestJson\(`\/agents\/\$\{agentId\}\/settings`/);
  assert.match(client, /requestJson\(`\/agents\/\$\{agentId\}\/settings\/test`/);
  assert.match(client, /requestJson/);
  assert.match(client, /response\.status === 204/);
  assert.match(client, /Node is unavailable/);
  assert.doesNotMatch(ui, /gateway_url.*fetch|fetch.*gateway_url/);
});
